version: '3'

services:
  app:
    build: .
    command: npm start
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/app  
  mysql:
    image: mysql
    container_name: 'database1'
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password 

  postgresql:
    image: postgres
    container_name: 'database2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
